### ISSUE TITLE
Landing on MUD (double penalty)

### ISSUE THREAD

**Issue by MarkMenzies** [EntelectChallenge/2020-Overdrive#10]
In the following console log, the Player1 bot lands on a MUD block, the issue is that it seems to be penalised in both turns for MUD block (y:1, x:43). The "hit_mud" state for turn 6 is correct, but note the state for turn 7. My question is whether this is correct, or whether the penalty should be incurred on turn 6 or turn 7, or indeed both?

```=======================================
Starting round: 6 
=======================================

=======================================
round:6
player: id:1 position: y:1 x:35 speed:6 state:HIT_MUD ... 
opponent: id:2 position: y:3 x:42 speed:8

[░░░░▓1░░▓░░░░▓░░░░░░░░▓░░░]
[░░Φ░▓▓░░░░░░░░░▓░░░░░░░░░░]
[▓░░»░▓░░░░░░2▓░░░░░░░░░░░░]
[░░░▓░░░▓░░░░░░░░▓░░░░░▓░░░]
=======================================
C;6;ACCELERATE
C;6;ACCELERATE
=======================================
Completed round: 6 
=======================================

=======================================
Starting round: 7 
=======================================

=======================================
round:7
player: id:1 position: y:1 x:43 speed:6 state:HIT_MUD ... 
opponent: id:2 position: y:3 x:51 speed:8

[▓░░░░1░░░░░░░░▓░░░░░░░░░░░]
[░░░░░░░▓░░░░░░░░░░░░░░░░░░]
[░░░░░▓░░░░░░░2░░░░░░░░░░░░]
[░░░░░░░░▓░░░░░▓░░░░░░░░░░░]
=======================================
C;7;ACCELERATE
C;7;USE_BOOST
=======================================
Completed round: 7 
=======================================

**Comment by Arne27** [comment]
Hi MarkMenzies.

I am currently investigating this and I hope to have an answer for you soon. 

Thanks for bringing this to our attention

**Comment by Arne27** [comment]
Hi @MarkMenzies 

From my investigation I don not think that there is a bug. If you look at the snippet that you posted then it looks like you have had some unlucky map generation. 

In round six your bot actually hit a mud block the # behind the 1.
In round 7 your bot hit another mud block that was on its path, the # behind the 1.

This is the intended behavior.

Starting round: 6 
=======================================

=======================================
round:6
player: id:1 position: y:1 x:35 speed:6 state:HIT_MUD ... 
opponent: id:2 position: y:3 x:42 speed:8

[░░░░#1░░▓░░░░▓░░░░░░░░▓░░░]
[░░Φ░▓▓░░░░░░░░░▓░░░░░░░░░░]
[▓░░»░▓░░░░░░2▓░░░░░░░░░░░░]
[░░░▓░░░▓░░░░░░░░▓░░░░░▓░░░]
=======================================
C;6;ACCELERATE
C;6;ACCELERATE
=======================================
Completed round: 6 
=======================================

=======================================
Starting round: 7 
=======================================

=======================================
round:7
player: id:1 position: y:1 x:43 speed:6 state:HIT_MUD ... 
opponent: id:2 position: y:3 x:51 speed:8

[#░░░░1░░░░░░░░▓░░░░░░░░░░░]
[░░░░░░░▓░░░░░░░░░░░░░░░░░░]
[░░░░░▓░░░░░░░2░░░░░░░░░░░░]
[░░░░░░░░▓░░░░░▓░░░░░░░░░░░]
=======================================
C;7;ACCELERATE
C;7;USE_BOOST
=======================================
Completed round: 7 
=======================================


Please let me know if this helps?

**Comment by MarkMenzies** [comment]
Thanks for checking and I see what you saying, I'll keep an eye out going forward. Cheers.

**Comment by styphoiz** [comment]
This is the same behaviour when dropping oil.
