### ISSUE TITLE
Unexpected Maximum Speed After Fixing

### ISSUE THREAD

**Issue by Quiescent** [EntelectChallenge/2020-Overdrive#106]
I've encountered a few scenarios where boosting or accelerating after fixing damage results in a slower speed than expected.

Gawie pointed this bug out on the balancing thread: https://forum.entelect.co.za/t/phase-3-balancing-issues-changes/1065/16

I think that I found the problem.
The `CarGamePlayer` class contains a variable called `maxSpeedState`.
`maxSpeedState` is updated during a call to `reduceMaxAllowableSpeed`.
`reduceMaxAllowableSpeed` is called all over the show:
* when the car hits a wall,
* when the car hits a cyber truck,
etc.

It is *not* called when we fix damage(!)

```scala
def fixDamage() = {
        setState(Config.FIX_CAR_PLAYER_STATE)
        val carIsDamaged = damage > 0
        if (carIsDamaged){
            damage -= Config.DAMAGE_REPAIR_VALUE;
        }
        capDamageAtZero()
    }
```

I have a branch ready which I'll create a pull request from to address this issue.

**Comment by Quiescent** [comment]
I've added a test to PR #107 which fails as the first commit and then fixed that test with the subsequent commit.

**Comment by Quiescent** [comment]
I've added a failing test as the first commit in this PR.
The second commit fixes the test and the third renames the function to reflect what it does more accurately.

**Comment by KyleMcAllister** [comment]
Hello @Quiescent , thank you for this. Everything looks legit. This will be a part of the next release 👍
