### ISSUE TITLE
Accelerated past maximum speed

### ISSUE THREAD

**Issue by Quiescent** [EntelectChallenge/2020-Overdrive#108]
I've encountered the following situanion:
```
round:40
player: id:1 position: y:4 x:218 speed:5 state:USED_BOOST statesThatOccurredThisRound:USED_BOOST boosting:true boost-counter:5 damage:4 score:18 powerups: LIZARD:3, TWEET:3, EMP:1, OIL:2, BOOST:2
opponent: id:2 position: y:3 x:230 speed:3

[░░░░░░░▓░░░░░░░░░▓▓▓░░░░░░]
[░»░░░░░░#░░░░░░░#▓░▓#░░░░░]
[░»░░░»░░░#░░░░░░▓2░#▓#░░░░]
[░░░░░1░░░░▓#░░░#▓░░░░▓▓░░░]
======================================================================================================
Received command C;40;ACCELERATE
round:41
player: id:1 position: y:4 x:224 speed:0 state:HIT_WALL statesThatOccurredThisRound:ACCELERATING, HIT_MUD, HIT_WALL boosting:false boost-counter:0 damage:6 score:10 powerups: LIZARD:3, TWEET:3, EMP:1, OIL:2, BOOST:2
opponent: id:2 position: y:4 x:232 speed:3

[░▓░░░░░░░░░▓▓▓░░░░░░░#░Φ»»]
[░░#░░░░░░░#▓░▓#░░░░░░##░*░]
[░░░#░░░░░░▓#░#▓#░░░░░#░░*░]
[░░░░▓1░░░#▓░░2░▓▓░░░░▓░░»░]
======================================================================================================
```

The scenario doesn't make sense to me because player one should have been capped at 5 and landed on the mud, and not the wall.
I wrote a test to replicate the bug, and in the test, it works perfectly.
i.e. in the test, the car is damaged and then accelerates.
It then lands five blocks ahead and not six (which happens above)
This bug is particularly vexing because the car is now stuck on the wall and can't move at all.

**Comment by kobus-v-schoor** [comment]
Hi, I think I've found a possibly related bug, in my case it triggered when trying to boost. I'm running a starter pack with the new max speed fixes by @Quiescent. Same idea, I boosted while I had some damage, expecting the maximum movement to be capped at the max speed of 9, but I end up moving as if though the speed was uncapped:

```
pos: (157, 4) -> (172, 4), speed: 6, damage: 1
cmd: USE_BOOST
state: FIXED_CAR
[#▓░░░░░#▓░░░░░T░░░░░#░▓▓▓▓]
[░░▓#░░░#▓#░░░░░Φ░░░░░░░▓▓░]
[░░░░▓▓▓▓▓#░░»░░░░░░░░T░#▓░]
[░░░░░1▓▓▓#░░Φ░»░∱░░T░░░░▓#]
```

Another example from same match:
```
pos: (899, 4) -> (914, 4), speed: 6, damage: 1
cmd: USE_BOOST
state: FIXED_CAR
[░░░░░░░░#▓▓▓▓#░░░░░░░░░░░░]
[░░░░░░░░░░░░▓░░░░░░░░░░░░░]
[░░TΦ░░░░*░░░∱▓#░░░░░░░░░░░]
[░░░T░1░░░░░░Φ▓░Φ░░░░░░░░░░]
```

I found a number of these examples in the same match, all of them the same (boost with 1 damage, end up 15 blocks ahead instead of 9)

**Comment by KyleMcAllister** [comment]
Hello @Quiescent and @kobus-v-schoor just checked and can confirm boosting bypasses damage (which is not intended). This will be fixed
