### ISSUE TITLE
Readme - Improve starter bot guidelines 

### ISSUE THREAD

**Issue by Mistborn94** [EntelectChallenge/2020-Overdrive#11]
Starter bot readme should include guidelines on submitting new starter bots. 

See 2019 for details https://github.com/EntelectChallenge/2019-Worms/tree/develop/starter-bots

**Comment by Jana-Wessels** [comment]
Awaiting feedback from Marno on the docker section.

**Comment by Mistborn94** [comment]
@Jana-Wessels Status on this?

**Comment by Jana-Wessels** [comment]
@Mistborn94 I checked in with Marno again he is still compiling all the information and is chatting to Privolin as well. Do you want me to do an initial one saying the docker information will follow?

**Comment by Mistborn94** [comment]
Yes please - at least so the logic required is present

**Comment by Mistborn94** [comment]
@Jana-Wessels Status update on this?

**Comment by Jana-Wessels** [comment]
@Mistborn94, I have added the deadline of the bots and a reference to the old docker info. I followed up with the cloud team but they didn't have the info yet, will follow up with them again tomorrow.
