### ISSUE TITLE
Damage not capped at 6 when hitting cybertruck

### ISSUE THREAD

**Issue by kobus-v-schoor** [EntelectChallenge/2020-Overdrive#113]
When hitting a cybertruck your damage can go above 6. I think the problem lies here:
[permalink to line](https://github.com/EntelectChallenge/2020-Overdrive/blob/7e4d911aa785cf4ee908766cdbdbcb6f465df906/game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/game/CarGamePlayer.scala#L367). The damage is increased but `capDamageAtSix()` isn't called.

```scala
    def hitCyberTruck() = {
        val allowStop : Boolean = false
        setState(Config.HIT_CYBER_TRUCK_PLAYER_STATE)
        reduceSpeedToLevel(allowStop, Config.SPEED_STATE_1)
        updateScore(Config.HIT_CYBERTRUCK_SCORE_PENALTY)
        damage += Config.DAMAGE_CYBERTRUCK;
        recalculateMaxAllowableSpeed()
    }
```

**Comment by Arne27** [comment]
@kobus-v-schoor Thanks for raising this, We are having a look
