### ISSUE TITLE
Player 2's speed gets reduced differently than player 1's when getting hit by EMP

### ISSUE THREAD

**Issue by kobus-v-schoor** [EntelectChallenge/2020-Overdrive#117]
I've encountered the following situation comparing two identical bots:

- When player 2 uses an EMP on player 1, player one makes their normal move as they should, and only at the next turn is their speed reduced to 3
- When player 1 uses an EMP on player 2, player two's speed is immediately reduced to 3, and they only move 3 blocks.

The following is an extract from two different matches, both with the same seed and two identical bots, but swapped ids. In the first example player 2 uses an EMP on player one. As can be seen player one still moves at their current speed, and then the next round their speed is reduced to 3

```
A
pos: (66, 4) -> (80, 3), speed: 15, damage: 0
cmd: TURN_LEFT
[░░░░░░░░░░░░░░░░▓Φ∱░░░░░░░]
[░░░░░░░░░▓░░░░░T░░░░T░░░░░]
[T░░░░░░░░░░░░░░░░░░░░░T░░░]
[*░░░░1»░░░░░░░▓░░░░░»░▓░░░]

B
pos: (57, 4) -> (66, 4), speed: 9, damage: 0
cmd: USE_EMP
state: TURNING_RIGHT
[░░░░░░░░░░░░░░░░░░░░░░░░░▓]
[░░░░░░░░░░░░░░░░░░▓░░░░░T░]
[░░░░░░░░░T░░░░░░░░░░░░░░░░]
[░░░░░2░░**░░░░1»░░░░░░░▓░░]
```

In this example, its the exact same two bots but their ids are swapped. But, as can be seen, player 2 only moves 3 blocks (whereas player 1 moved 15)

```
A
pos: (57, 4) -> (66, 4), speed: 9, damage: 0
cmd: USE_EMP
[░░░░░░░░░░░░░░░░░░░░░░░░░▓]
[░░░░░░░░░░░░░░░░░░▓░░░░░T░]
[░░░░░░░░░T░░░░░░░░░░░░░░░░]
[░░░░░1░░**░░░░2»░░░░░░░▓░░]

B
pos: (66, 4) -> (68, 3), speed: 15, damage: 0
cmd: TURN_LEFT
[░░░░░░░░░░░░░░░░▓Φ∱░░░░░░░]
[░░░░░░░░░▓░░░░░T░░░░T░░░░░]
[T░░░░░░░░░░░░░░░░░░░░░T░░░]
[*░░░░2»░░░░░░░▓░░░░░»░▓░░░]
```

Currently running the development branch of the engine with HEAD at 7e4d911, which includes the new map generation and max speed after fixing changes

**Comment by kobus-v-schoor** [comment]
Looking at the engine code, I think it might be due to this piece [here](https://github.com/EntelectChallenge/2020-Overdrive/blob/7e4d911aa785cf4ee908766cdbdbcb6f465df906/game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/game/CarGameRoundProcessor.scala#L28):

```scala
 for ( i <- gamePlayers.indices) {
      val gamePlayer = gamePlayers(i)
      val commandText = commandsToProcess.get(gamePlayer).get(0).getCommand
      var playerCommand: RawCommand = commandFactory.makeCommand(commandText)
      playerCommand.performCommand(gameMap, gamePlayer)
    }
```

I'm guessing when player 1 uses an EMP, player 2's speed is modified immediately, and only after that is player 2's moves executed. When player 2 uses an EMP on player 1, player 1's moves have already been executed and their speed is only reduced at the next round

**Comment by kobus-v-schoor** [comment]
I've just went through the rules again, and I just saw that an EMP is supposed to "stop them in their tracks for the rest of the round, and then reduce their speed to 3" (from game rules). I don't think I've seen the EMP actually stop any of the players before (also visible in the first comment in this issue)

**Comment by KyleMcAllister** [comment]
Hi @kobus-v-schoor thanks for highlighting this. Based on this and an issue raised on the forum we are going to have another look at the EMP functionality so that it does behave as stated in the game rules. We will have a fix for this in the next release.

**Comment by kobus-v-schoor** [comment]
@ThePheonixGuy, @KyleMcAllister  - I just went through the existing [test](https://github.com/EntelectChallenge/2020-Overdrive/blob/34b0af4015858c07da908083dcc87c062339c0b9/game-engine/src/test/scala/Command_Use_Emp_Tests.scala#L103) (same test as in commit 34b0af4 which was added to presumably test this bug), I just want to clarify why that test doesn't actually check for this bug. The test only verifies that player 1's speed is reduced to a speed of 3 after the round has been processed, which is not the issue that I raised here. The issue is that

- When player 1 uses an EMP on player 2, player 2's speed is immediately reduced to 3 - so regardless of player 2's speed/command for the round, player 2 only moves 3 blocks ahead (2 if they turn, as in the example)
- When player 2 uses an EMP on player 1, player 1's speed is only reduced to 3 after the round is processed. So, player 1 still moves their original amount of blocks (15 in the example) and only after the round is processed is their speed reduced to 3.

So the issue is not whether both player's speed is reduced to 3 (which is what the test verifies), the issue is at what point does this happen because this influences how far the player moves in the round that they were hit.

Sorry if I'm jumping the gun here, just wanted to make sure that there is no ambiguity in how I described the bug seeing as the deadline is getting closer.

**Comment by KyleMcAllister** [comment]
Hello @kobus-v-schoor not a problem. We are still in progress with the fixes for the EMP issues stated. The goal is to ensure:
- EMP works as specified in readme (i.e. player affected does not move and has speed reduced to 3)
- Both players are affected by EMP equally (as stated as the bug in this issue) i.e. there are no concurrency issues with EMP logic

Appreciate the diligence tho 😃
