### ISSUE TITLE
Turning onto a cybertruck doesn't trigger a collision

### ISSUE THREAD

**Issue by kobus-v-schoor** [EntelectChallenge/2020-Overdrive#119]
If a player is positioned like this:

```
|C| | | |
|1| | | |
```

or this

```
|1| | | |
|C| | | |
```

and they turn left/right onto the cybertruck it doesn't trigger a collision and the player just goes on as normal. The issue lies [here](https://github.com/EntelectChallenge/2020-Overdrive/blob/309ed8b798a7932c7330034e2600af924be3ca4a/game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/map/CarGameMap.scala#L171):

```scala
  val blockWithCyberTruckInMiddleOfPath = blocks.find(b => (b.getPosition().getLane() == endLane
  && b.getPosition().getBlockNumber() > startBlockNumber
  && b.getPosition().getBlockNumber() <= endBlockNumber-1)
  && b.isOccupiedByCyberTruck()
)
val lastBlockWithCyberTruck = blocks.find(b => b.getPosition().getLane() == endLane
  && b.getPosition().getBlockNumber() == endBlockNumber
  && b.isOccupiedByCyberTruck()
)
val middleOfPathHasCyberTruckAndPlayerIsOnTheGround = blockWithCyberTruckInMiddleOfPath.isDefined && !x.getPlayer().isLizarding
val playerCollidesWithCyberTruck = middleOfPathHasCyberTruckAndPlayerIsOnTheGround || lastBlockWithCyberTruck.isDefined
```

This only checks if there is a cybertruck in the player's path by checking the player's x + 1 onward, so when you turn onto the block to the immediate left or right of the player it is not checked for cybertrucks.

**Comment by KyleMcAllister** [comment]
Thanks for this, will be fixed in the next release
