### ISSUE TITLE
If your boost counter runs out your speed gets restored to 9 regardless of damage

### ISSUE THREAD

**Issue by kobus-v-schoor** [EntelectChallenge/2020-Overdrive#120]
If you boost to a lower speed, say 6, and you're able to maintain the boost until your boost counter runs down to 0 your speed will get restored to MAXIMUM_SPEED, or 9, regardless of the damage your car may have. Issue lies here https://github.com/EntelectChallenge/2020-Overdrive/blob/309ed8b798a7932c7330034e2600af924be3ca4a/game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/game/CarGamePlayer.scala#L279

```scala
    def tickBoost() = {
        boostCounter -= 1
        val boostOver = boostCounter == 0
        if (boostOver) {
            boosting = false
            speed = MAXIMUM_SPEED
            setState(Config.NOTHING_PLAYER_STATE)
        }
    }
```

**Comment by KyleMcAllister** [comment]
Hi @kobus-v-schoor yeah I agree with the observation here. That should be maxSpeedState rather than max speed. Will have a fix in for the next release
