### ISSUE TITLE
If you fix while on a cybertruck it triggers a cybertruck collision

### ISSUE THREAD

**Issue by kobus-v-schoor** [EntelectChallenge/2020-Overdrive#121]
Whereas the bug where the current terrain gets re-applied to the player if they fix on a special terrain block has been fixed, it seems that the bug is still present for cybertrucks since their collision logic is separate from the rest. So, if you fix and you somehow happen to be on a cybertruck a cybertruck collision is triggered even though it shouldn't.

**Comment by KyleMcAllister** [comment]
That's an interesting one. The only way that could happen is if player A is on block (x,y) and player A chooses to fix and player B chooses to drop a cyber truck on block (x,y). Given that we ignore the start block of each round the truck should be ignored. Will write a test and should that not be the case, will resolve. Thanks for the heads up

**Comment by KyleMcAllister** [comment]
Have a test to prove the expected behavior is what occurs.

**Comment by kobus-v-schoor** [comment]
Hi @KyleMcAllister, thanks for looking at this - I just had a look at the new test case that you added but I think the test does not actually trigger the bug - as I understand it, the test case goes as follows:

1. Round 1: player 2 fixes and player 1 places a tweet at player 2's position
2. Cybertruck then gets placed at end of round 1
3. round 2, player 1 and 2 does a nothing command

In the above case player 2 is never actually stationary while on top of the cybertruck, so it doesn't trigger the bug.

The sequence of how I observed the bug in my own tests:

1. Round 1: Player 1 places a cybertruck at position (x, y), Player 2 takes a move such that they end up on (x, y)
2. Cybertruck then gets placed at position (x, y) (player 2's current position)
3. Round 2: Player 2 now issues a fix command, which causes them to be stationary on top of the already placed cybertruck. This triggers the collision.

**Comment by KyleMcAllister** [comment]
Hello @kobus-v-schoor I see your point. Will add an additional test for the scenario you described to see what happens (worth noting the expected behavior is for player 2 to be unaffected by the cyber truck)

**Comment by KyleMcAllister** [comment]
Hello @kobus-v-schoor can confirm your scenario revealed a bug. It will be fixed in the next release
