### ISSUE TITLE
Player 2 speed after getting hit by EMP not correctly reduced in edge case

### ISSUE THREAD

**Issue by kobus-v-schoor** [EntelectChallenge/2020-Overdrive#124]
If player 2 takes an action that modifies their speed (acceleration, boosting or deceleration, I confirmed cases for all 3), the speed modification gets applied after the EMP speed penalty. This means that, for example, if player 1 uses an EMP on player 2 and player 2 uses a boost, player 2 is stopped for the round, but on the next round their speed is 15 (instead of 3) because the boost was applied after their speed was reduced to 3 by the EMP. This does not happen when player 2 uses an EMP on player 1 (probably since player 1's command is processed and then only after that is their EMP speed penalty applied).

**Comment by kobus-v-schoor** [comment]
I just went through the existing tests and I see that there is a test that verifies this behaviour and actually checks that it should happen. Does this mean that this is the intended behaviour? Because if so, that means that the issue is actually the other way around - player 1's behaviour is then the problem. I could not find a similar test as the one below which checks for player 1's behaviour. The line in question is at the very bottom of the test, and checks that player 2's speed is SPEED_STATE_2 if they accelerate while being hit by an EMP.

https://github.com/EntelectChallenge/2020-Overdrive/blob/3a269c30ab129a2492203b467463be3b35738d7f/game-engine/src/test/scala/Command_Use_Emp_Tests.scala#L201

```scala
  test("Given player1 with emp behind player2, one lane away, when USE_EMP command player2 slows down") {
    initialise()
    val gameMap = TestHelper.initialiseGameWithNoMapObjects()
    val carGameMap = gameMap.asInstanceOf[CarGameMap]

    val testGamePlayer1 = TestHelper.getTestGamePlayer1()
    val testCarGamePlayer1 = testGamePlayer1.asInstanceOf[CarGamePlayer]
    TestHelper.putPlayerSomewhereOnTheTrack(carGameMap, testCarGamePlayer1.getGamePlayerId(), 3, 40)

    val testGamePlayer2 = TestHelper.getTestGamePlayer2()
    val testCarGamePlayer2 = testGamePlayer2.asInstanceOf[CarGamePlayer]
    TestHelper.putPlayerSomewhereOnTheTrack(carGameMap, testCarGamePlayer2.getGamePlayerId(), 4, 100)

    testCarGamePlayer1.speed = Config.SPEED_STATE_3
    testCarGamePlayer2.speed = Config.SPEED_STATE_3

    testCarGamePlayer1.pickupEmp()
    TestHelper.processRound(gameMap, nothingCommand, nothingCommand)
    TestHelper.processRound(gameMap, useEmpCommand, nothingCommand)

    assert(testCarGamePlayer2.speed == Config.SPEED_STATE_1)


    testCarGamePlayer1.pickupEmp()
    TestHelper.processRound(gameMap, nothingCommand, accelerateCommand)
    TestHelper.processRound(gameMap, useEmpCommand, accelerateCommand)

    assert(testCarGamePlayer2.speed == Config.SPEED_STATE_2)
  }

```

**Comment by KyleMcAllister** [comment]
Hi @kobus-v-schoor  thanks for bringing this to our attention. We will investigate and revert when we have a solution
