### ISSUE TITLE
Console example doesn't exist

### ISSUE THREAD

**Issue by styphoiz** [EntelectChallenge/2020-Overdrive#18]
https://github.com/EntelectChallenge/2020-Overdrive/blob/master/game-engine/assets/example-state/console.txt points to a non-existant page.

**Comment by KyleMcAllister** [comment]
Hello @styphoiz the correct link is https://github.com/EntelectChallenge/2020-Overdrive/blob/master/game-engine/example-assets/console.txt and I believe the readme has been updated accordingly so going to close this
