### ISSUE TITLE
State incorrectly showing as HIT_MUD even though I'm not close

### ISSUE THREAD

**Issue by styphoiz** [EntelectChallenge/2020-Overdrive#23]
See console details below and yes I counted.

round:22
player: id:1 position: y:2 x:165 speed:6 state:HIT_MUD boosting:false boost-counter:0 powerups: OIL:1
opponent: id:2 position: y:2 x:112 speed:8

[░▓░░░░░░▓░░░░░░░░░░░░░░░░░]
[░░░░░1░░░░░░░░░░░░░░░▓░░░░]
[░Φ░▓░░░░░░░░░░░»░░Φ░░░░░░▓]
[░░░░░░░░░░▓░░░░░░»░░░░░░░░]
======================================================================================================
C;22;ACCELERATE
C;22;ACCELERATE
=======================================
Completed round: 22 
=======================================

=======================================
Starting round: 23 
=======================================

======================================================================================================
round:23
player: id:1 position: y:2 x:173 speed:6 state:HIT_MUD boosting:false boost-counter:0 powerups: OIL:1
opponent: id:2 position: y:2 x:121 speed:9

[▓░░░░░░░░░░░░░░░░░░░░░░░░░]
[░░░░░1░░░░░░░▓░░░░░░░░░░░░]
[░░░░░░░»░░Φ░░░░░░▓░░░░░░░░]
[░░▓░░░░░░»░░░░░░░░░░░░░░░░]
======================================================================================================

C;23;ACCELERATE
C;23;TURN_LEFT
=======================================
Completed round: 23 
=======================================

=======================================
Starting round: 24 
=======================================

======================================================================================================
round:24
player: id:1 position: y:2 x:181 speed:6 state:HIT_MUD boosting:false boost-counter:0 powerups: OIL:1
opponent: id:2 position: y:1 x:129 speed:8

[░░░░░░░░░░░░░░░░░░░░▓▓░▓▓░]
[░░░░░1░░░░░░░░░░░░░░░░░░░░]
[░░Φ░░░░░░▓░░░░░░░░░░░▓░░░»]
[░»░░░░░░░░░░░░░░░░░░░░░░░░]

C;24;ACCELERATE
C;24;TURN_LEFT

**Comment by styphoiz** [comment]
Here’s another one, I should have still been in Boost here

Starting round: 39
======================================================================================================
round:39
player: id:1 position: y:4 x:327 speed:8 state:HIT_MUD boosting:false boost-counter:0 powerups: OIL:3, BOOST:1
opponent: id:2 position: y:4 x:236 speed:8

[░░░░░░▓░░░░▓░»░░░▓░░░░░▓░░]
[░░░░░░░░░▓░░░░░░░▓░░░░░░Φ░]
[░▓░░░░░░░»░▓▓░░▓▓░░░░░░▓░░]
[░░▓░░1░░░░░░░░░░░░░░░░░░░░]
C;39;USE_BOOST
C;39;TURN_LEFT
Completed round: 39
=======================================
Starting round: 40
======================================================================================================
round:40
player: id:1 position: y:4 x:342 speed:9 state:HIT_MUD boosting:false boost-counter:0 powerups: OIL:3
opponent: id:2 position: y:3 x:243 speed:8

[░░▓░░░░░▓░░▓░░░░░░░░░░░░░░]
[░░▓░░░░░░Φ░░░░▓░░░░░░░░░░░]
[▓▓░░░░░░▓░░░░░░░░░░░░░░░░▓]
[░░░░░1░░░░░░░░░░░░░Φ░░░▓░░]

**Comment by KyleMcAllister** [comment]
@styphoiz apologies for the delay in replying to this issue. This is my next mission, will revert when I have an update for you 👍
