### ISSUE TITLE
Blocks not sorted in lane by x value

### ISSUE THREAD

**Issue by Blaarkies** [EntelectChallenge/2020-Overdrive#24]
https://forum.entelect.co.za/t/block-order-inside-lanes/908

In the json file, the blocks are in a seemingly random order (they are at least in the correct lane though)

The game-engine json renderer print the game state into this json file, but is missing some sorting operation

**Comment by Jana-Wessels** [comment]
I think this was resolved, happened on one version of the game engine but was fixed. Will reopen if I find it occurring again.
