### ISSUE TITLE
Accessing and setting the system class loader is not supported in recent versions of Java

### ISSUE THREAD

**Issue by Quiescent** [EntelectChallenge/2020-Overdrive#32]
Related: https://github.com/EntelectChallenge/2020-Overdrive/issues/6

# Introduction
In the `GameBootStrapper` class, the system class loader is overridden.
https://github.com/EntelectChallenge/2020-Overdrive/blob/849c2c179f2e61c89e057bcbd3da4663d743f7d4/game-runner/src/main/java/za/co/entelect/challenge/engine/bootstrapper/GameBootstrapper.java#L206

I assume (and please correct me if I'm wrong!) that this was done because the intention is to dynamically load the `game-engine.jar` jar file.

# Problem
Unfortunately, this method of setting the system class loader is not supported in recent versions of java and fails with the following error:
```bash
bash-5.0$ make run
java -jar target/game-runner-jar-with-dependencies.jar
Exception in thread "main" java.lang.NoSuchFieldException: scl
	at java.base/java.lang.Class.getDeclaredField(Class.java:2412)
	at za.co.entelect.challenge.engine.bootstrapper.GameBootstrapper.setupSystemClassloader(GameBootstrapper.java:206)
	at za.co.entelect.challenge.engine.bootstrapper.GameBootstrapper.main(GameBootstrapper.java:54)
make: *** [makefile:5: run] Error 1
```

# Proposed Solution
I propose that we instead load the game engine jar like one would any other jar: by setting the classpath for java when it's run.
I'm about to submit a pull request which:
 - adds a root level makefile for convenience to build the whole project;
 - adds a dependency from `game-runner` to `game-engine`;
 - publishes `game-engine` to your local maven cache for convenience (I recommend that the maintainers set a fixed version and publish it for tournaments!);
 - loads the jar using the classpath in the makefile inside of `game-runner`;

I've tested these changes on my Linux machine, and they require testing on other platforms.

**Comment by demaniak** [comment]
Hi @Quiescent - I assume you mean java 12+ ?
I'm running 11 (Zulu), and things work fine for me currently (apart from the annoying message about " An illegal reflective access operation has occurred")..

**Comment by Quiescent** [comment]
@demaniak yes.  I thought it would be the case for 11+ as well though.
Thanks for the correction :+1:

**Comment by Quiescent** [comment]
In fact.  I appear to be using 13.  So I'm unsure about whether it works on 12.  Others are welcome to contribute their experiences :)

**Comment by demaniak** [comment]
Well, just to add (now that I properly reread the warning issued by 11) - 11 does actually complain about the exact same thing higher versions (or at least 13) is failing on.
So I guess ignore warnings at your peril!

**Comment by Mistborn94** [comment]
Hi All
This issue has been resolved on the develop branch :) We will be releasing a new starter pack soon that contains the fix.
