### ISSUE TITLE
Hitting mud penalty incorrectly calculated

### ISSUE THREAD

**Issue by kobus-v-schoor** [EntelectChallenge/2020-Overdrive#35]
Hi,

Currently there still seems to be a bug where the speed penalty for hitting mud isn't correctly calculated although it seems to be fairly rare. I've only been able to reproduce it twice (current release at the time of writing is 2020.01.4, so after the previous fix where multiple hits weren't counted).

For the first example a TURN_LEFT is issued while boosting. The expected speed penalty would be 15->9->8->6->3 (hitting 4 mud blocks) but in this case the resulting speed was 6. 

```
==============================
round:32
player: id:1 position: y:3 x:290 speed:15 state:NOTHING boosting:true boost-counter:4 powerups: OIL:5, BOOST:3
opponent: id:2 position: y:2 x:178 speed:6

[░░░░»░░░▓░▓░░░░░░░▓░░░░░░░]
[░░░░░▓░░░░░▓▓▓░░░░░░░░░░░░]
[░░░░░1░░░░░░▓░░░░░░░░▓░░░░]
[░░░░░░░░░░░░░░░░▓░▓░░░▓░░▓]
==============================

CMD: TURN_LEFT

==============================
round:33
player: id:1 position: y:2 x:304 speed:6 state:HIT_MUD boosting:false boost-counter:0 powerups: OIL:5, BOOST:3
opponent: id:2 position: y:3 x:183 speed:6

[░░░░▓░░░░░░░░░░░░░░░░░░░░░]
[░░░░░1░░░░░░░░▓░▓░░░░░░░░▓]
[░░░░░░░▓░░░░░░░░░░░░▓░░░░░]
[░░▓░▓░░░▓░░▓░░░░Φ░░░░░░░░»]
==============================
```
In the next example a TURN_RIGHT command was issued and there is an expected penalty of hitting one mud block so the speed should be 8->6. The actual resulting speed stayed 8.

```
==============================
round:133
player: id:1 position: y:3 x:1435 speed:8 state:TURNING_RIGHT boosting:false boost-counter:0 powerups: OIL:6
opponent: id:2 position: y:3 x:621 speed:3

[░░░░░░░░░░░░░░░░»░░░░░░░░▓]
[░░░░░░░░░░░░░▓░░▓░░░░░»░░░]
[░░░░░1░░░░░░░░░░░▓░░░░░░▓░]
[░░░░░▓░»░░░░░▓░░░░░»░░░░░░]
==============================

CMD: TURN_RIGHT

==============================
round:134
player: id:1 position: y:4 x:1442 speed:8 state:TURNING_RIGHT boosting:false boost-counter:0 powerups: OIL:6, BOOST:1
opponent: id:2 position: y:2 x:623 speed:3

[░░░░░░░░░»░░░░░░░░▓░░▓░░░░]
[░░░░░░▓░░▓░░░░░»░░░░░░▓░░▓]
[░░░░░░░░░░▓░░░░░░▓░»░░░░░░]
[»░░░░1▓░░░░░»░░░░░░░░░▓░░░]
==============================
```

In both examples the final endpoint was calculated correctly and in the second example the boost pickup was successful. In the first example the player was boosting and in the second one not, so the only common denominator between the two examples were that both were turning.

If you need more details please let me know.

**Comment by GawieJooste** [comment]
I also observed the same issue when a powerup is next to the car, and the TURN command is issued, the powerup will not be picked up. Just like the mud is missed in the original post by @kobus-v-schoor. 

This behaviour is unexpected since the game rules state:
_"The first block the bot moves will be directly to the left/right, and then the rest of the blocks directly forward in the new lane."_

**Comment by demaniak** [comment]
Could the problem possibly related [to this?](https://github.com/EntelectChallenge/2020-Overdrive/pull/30/files/e2d90bae4fbe578a769317c1d07c0b16d82203f1#diff-41c95c3cbd26bc3b6c5cb48c8dea6b7bR293)

I might be missing something, but it feels like the lane value should also be modified there when turning?

**Comment by RoboBuffalo** [comment]
The issue also appears when you accelerate and the mud in your way won't impact and speed remains as was if it was maximum.
