### ISSUE TITLE
Race fairness on start from generated map is scewed to one of the bots

### ISSUE THREAD

**Issue by tylergoodburn** [EntelectChallenge/2020-Overdrive#43]
On start, when the map is generated, depending on the positioning of the bots on the map and how the map is generated one of the bots has an advantage based on where obstacles are situated.

Forum link:
https://forum.entelect.co.za/t/race-fairness/932

**Comment by KyleMcAllister** [comment]
This has been addressed by the new way we run tournament matches i.e.:
- run race 1
- run race 2 with player positions swapped
- winner is player that won both races
- if tie winner is player with highest total score
