### ISSUE TITLE
Oponent is not affected by oild drop when oil is dropped directly behind.

### ISSUE THREAD

**Issue by tylergoodburn** [EntelectChallenge/2020-Overdrive#45]
In the game when a bot drops an oil spill the opponent does not get affected by the obstacle if they are directly behind as it is already under the bot.

Forum link:
https://forum.entelect.co.za/t/drop-oil-when-opponent-directly-behind/936

**Comment by demaniak** [comment]
I believe this has been fixed recently (version 2.0+)

**Comment by KyleMcAllister** [comment]
@demaniak yup that was fixed by chaning the oil drop to behave as previously i.e. dropping underneath player rather than behind them
