### ISSUE TITLE
Mud missed with new release.

### ISSUE THREAD

**Issue by styphoiz** [EntelectChallenge/2020-Overdrive#47]
The speed below should've dropped as I would've hit mud on my right turn yet this still shows my speed as 15

Starting round: 10 
=======================================

======================================================================================================
round:10
player: id:1 position: y:1 x:72 speed:15 state:USED_BOOST boosting:true boost-counter:5 powerups: OIL:3
opponent: id:2 position: y:4 x:47 speed:8

[░░░░░1░░░░░░░░░░░░░▓░░░░░░]
[░░░░░▓░»░░░░░░░░░░░░░░░▓░░]
[░░░▓░░░░░░░░░░░░░░░░░▓░▓░░]
[░░░░░░░░░░░░░░░░░▓░░░░░░░░]
======================================================================================================
C;10;TURN_RIGHT
C;10;ACCELERATE
=======================================
Completed round: 10 
=======================================

=======================================
Starting round: 11 
=======================================

======================================================================================================
round:11
player: id:1 position: y:2 x:86 speed:15 state:TURNING_RIGHT boosting:true boost-counter:4 powerups: OIL:3, BOOST:1
opponent: id:2 position: y:4 x:56 speed:9

[░░░░░▓░░░░░░░░░░░░░▓░▓░▓▓░]
[░░░░░1░░░▓░░░░░░░░░░▓░▓░░░]
[░░░░░░░▓░▓░░░░░░▓░░▓▓»░░░░]
[░░░▓░░░░░░░░▓░░░░░░░░░░░░░]
======================================================================================================
C;11;ACCELERATE
C;11;TURN_LEFT

**Comment by styphoiz** [comment]
You can see the same problem here as well

Starting round: 12 
=======================================

======================================================================================================
round:12
player: id:1 position: y:2 x:101 speed:8 state:HIT_MUD boosting:false boost-counter:0 powerups: OIL:3, BOOST:1
opponent: id:2 position: y:3 x:64 speed:8

[░░░░▓░▓░▓▓░░░░░░░░░░░░░░▓░]
[░░░░░1░▓░░░░▓░░░░░░░░░░░░░]
[░▓░░▓▓»░░░░░░░▓░░░░░▓░░░Φ░]
[░░░░░░░░░░░░░░░▓░░░Φ░░░░░░]
======================================================================================================

=======================================
Completed round: 12 
=======================================

=======================================
Starting round: 13 
=======================================

======================================================================================================
round:13
player: id:1 position: y:3 x:108 speed:8 state:TURNING_RIGHT boosting:false boost-counter:0 powerups: OIL:3, BOOST:2
opponent: id:2 position: y:2 x:71 speed:8

[░▓▓░░░░░░░░░░░░░░▓░░░▓░░░▓]
[▓░░░░▓░░░░░░░░░░░░░░░░░░░▓]
[░░░░░1░▓░░░░░▓░░░Φ░▓░░░░░░]
[░░░░░░░░▓░░░Φ░░░░░░░░░▓▓░░]
======================================================================================================

C;13;TURN_LEFT
C;13;TURN_LEFT
=======================================
Completed round: 13 
=======================================

=======================================
Starting round: 14 
=======================================

======================================================================================================
round:14
player: id:1 position: y:2 x:115 speed:8 state:TURNING_LEFT boosting:false boost-counter:0 powerups: OIL:3, BOOST:2
opponent: id:2 position: y:1 x:78 speed:8

[░░░░░░░░░░▓░░░▓░░░▓░░░░░░░]
[░░░░░1░░░░░░░░░░░░▓░▓░░░░░]
[▓░░░░░▓░░░Φ░▓░░░░░░░░░░░▓░]
[░▓░░░Φ░░░░░░░░░▓▓░░░»░░░░░]
======================================================================================================

C;14;ACCELERATE
C;14;TURN_RIGHT
=======================================
Completed round: 14

**Comment by kobus-v-schoor** [comment]
I think this is probably the same bug as #35 and not due to the new release

**Comment by styphoiz** [comment]
Yes, this looks related, I don't recall seeing this behaviour when I was running with the earlier releases.

**Comment by styphoiz** [comment]
Related to https://github.com/EntelectChallenge/2020-Overdrive/issues/35
