### ISSUE TITLE
Speed state decrease incorrect (possibly)

### ISSUE THREAD

**Issue by gatkramp** [EntelectChallenge/2020-Overdrive#5]
Hello

I have noticed that if you hit multiple mud blocks in your turn, the speed_state is only lowered by 1. Is this intentional or possibly a mistake. eg.

![image](https://user-images.githubusercontent.com/8925826/77164435-ee22b480-6ab8-11ea-9480-053364f95315.png)

In round 69, Player 2 has a speed of 8. The next move it makes is to Turn Left.

![image](https://user-images.githubusercontent.com/8925826/77164518-23c79d80-6ab9-11ea-9cea-de68a47286e6.png)

In round 70, Player 2 has moved through 3 mud blocks, but only dropped 1 speed_state.

Is this correct?

**Comment by gatkramp** [comment]
Nope, cannot be right. If you hard-code the bot to always accelerate, it always wins.

Irrespective of how many mud blocks it hits, it currently only decreases with one speed state. If the bot accelerates during the next round, it will be back to the highest speed state. Thus, the bot drives through the map at a nice speed of 9 without being influenced by the mud blocks.

**Comment by KyleMcAllister** [comment]
Hello, we made a fix for this bug, and are looking to release it soon.
