### ISSUE TITLE
is-tournament-mode should be set to false as default

### ISSUE THREAD

**Issue by RossKohler** [EntelectChallenge/2020-Overdrive#52]
Anyone who tries to clone the repo fresh and run from source will have trouble because the game-runner tries to read environment variables (because is-tournament-mode:true in the game-runner-config). Should probably set that to false in the repo to save others from wasting the time I spent debugging the issue. Thanks

**Comment by KyleMcAllister** [comment]
Hello @RossKohler this will be changed with the next merge into master.
