### ISSUE TITLE
Python reference bot won't run - Invalid Position

### ISSUE THREAD

**Issue by clbuttic** [EntelectChallenge/2020-Overdrive#54]
When run in the starter pack, an AttributeError is thrown in the first round from line:

https://github.com/EntelectChallenge/2020-Overdrive/blob/87ecb122ae636fa35ead917f0115070e6e71e330/starter-bots/python3/PythonStarterBot.py#L122

player_info.position of type defined in Position.py does not have attributes named block and lane:

https://github.com/EntelectChallenge/2020-Overdrive/blob/87ecb122ae636fa35ead917f0115070e6e71e330/starter-bots/python3/Position.py#L1-L4

The game runner is then unable to run the python3 starter bot.

**Comment by KyleMcAllister** [comment]
Hello @clbuttic . This has been looked into and will be fixed with the next release.
