### ISSUE TITLE
Undefined behavior when both cars could hit a cybertruck

### ISSUE THREAD

**Issue by kobus-v-schoor** [EntelectChallenge/2020-Overdrive#70]
Hi, as far as I currently can tell the behavior of the engine when both cars is going to hit a cybertruck is not explicitly defined and depends on the order which players are stored in memory.

For instance, say the map currently looks like this:

`|1| |2| | | |C|`

Assuming that both players would hit the placed cybertruck, it would seem that it is possible that car 1 would hit the cybertruck, which removes it from the map, after which car 2 would not hit anything although it makes more sense to let 2 hit the cybertruck.

The reason I suspect this is the following - firstly, in this code block the list of players is determined by CarGameMap.getGamePlayers():

https://github.com/EntelectChallenge/2020-Overdrive/blob/d2bc0698f2b3bce3e0e6b69f701ad5e78a72b875/game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/game/CarGameRoundProcessor.scala#L16

```scala
  override def processRound(gameMap: GameMap, commandsToProcess: util.Map[GamePlayer, util.List[RawCommand]]): Boolean = {
    val carGameMap = gameMap.asInstanceOf[CarGameMap]
    val gamePlayers = carGameMap.getGamePlayers()
    val commandFactory = new CommandFactory
    for ( i <- gamePlayers.indices) {
      val gamePlayer = gamePlayers(i)
      val commandText = commandsToProcess.get(gamePlayer).get(0).getCommand
      var playerCommand: RawCommand = commandFactory.makeCommand(commandText)
      playerCommand.performCommand(gameMap, gamePlayer)
    }
```
which, in turn just loops through the players in no specific order:

https://github.com/EntelectChallenge/2020-Overdrive/blob/d2bc0698f2b3bce3e0e6b69f701ad5e78a72b875/game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/map/CarGameMap.scala#L88

```scala
    def getCarGamePlayers(): Array[CarGamePlayer] = {
        var carGamePlayers = new Array[CarGamePlayer](players.size())
        for (i <- 0 until players.size()) {
            val player = players.get(i)
            val gamePlayer = player.getGamePlayer
            val carGamePlayer = gamePlayer.asInstanceOf[CarGamePlayer]
            carGamePlayers(i) = carGamePlayer
        }
        return carGamePlayers
    }
```

Then, in CarGameMap.resolveCyberTruckCollisions() the players are again looped through, and the first player in the list of players to hit the cybertruck gets the penalty, after which the cybertruck is removed:

https://github.com/EntelectChallenge/2020-Overdrive/blob/d2bc0698f2b3bce3e0e6b69f701ad5e78a72b875/game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/map/CarGameMap.scala#L156

```scala
        ....
        stagedFuturePositions.foreach(x => {
                if(middleOfPathHasCyberTruckAndPlayerIsOnTheGround) {
                    val definedBlockWithCyberTruck = blockWithCyberTruckInMiddleOfPath.get
                    val adjustedNewLane = definedBlockWithCyberTruck.getPosition().getLane()
                    val adjustedNewBlockNumber = definedBlockWithCyberTruck.getPosition().getBlockNumber() - 1
                    val newFuturePosition = new BlockPosition(adjustedNewLane, adjustedNewBlockNumber)
                    x.setNewPosition(newFuturePosition)
                    x.getPlayer().hitCyberTruck()
                    definedBlockWithCyberTruck.removeCyberTruck()
                    playerHitCyberTruck = true
                }
        ....
```

Some order of precedence for the players hitting the cybertruck needs to be established or the cybertruck should only be removed at the end of the round. While in the first example it would work if the players were sorted by their x position, what would happen if the two players are in different lanes (at the same x position) and one player turns into the lane with the cybertruck? Currently the car collision logic only kicks in after the cybertruck collisions 

https://github.com/EntelectChallenge/2020-Overdrive/blob/d2bc0698f2b3bce3e0e6b69f701ad5e78a72b875/game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/game/CarGameRoundProcessor.scala#L25

so I'm guessing the car collision logic won't solve these kind of issues. I haven't actually tested this on the game engine, just currently in the planning phase and I realized the rules didn't specify what happens in this case.

**Comment by KyleMcAllister** [comment]
Thanks @kobus-v-schoor we will run simulation to see exactly what happens here. The expected behaviour in the situation you described is player 2 should be stuck behind the cyber truck and player 1 should be stuck behind player 2. If that is not the case we will make adjustments accordingly

**Comment by kobus-v-schoor** [comment]
Thanks @KyleMcAllister - while the collision logic can probably take care of this when one of the players rear-end the other, what happens when there is no collision? For example given the map below and that both players are driving at the same speed, what happens if player 2 takes a right turn? In this case there normally wouldn't be any collision so the collision logic won't kick in.

```
| | |2| | |
|1| | | |C|
```

**Comment by Jana-Wessels** [comment]
Hi Kobus,

I have added test cases for the following two cases https://github.com/EntelectChallenge/2020-Overdrive/pull/80 and the out comes were as follows:

**Case 1:**
|1|  |2|  |  |  |C| 

Car 2 gets stuck behind the cybertruck and car 1 gets stuck behind 2
|  |  |  |  |1|2|C|

**Case 2:**
|  |  |2|  |  |  |  | 
|1|  |  |  |  |  |C| 

For example given the map above and that both players are driving at the same speed, what happens if player 2 takes a right turn?

This goes to:
|  |  |  |  |  |2|  | 
|  |  |  |  |  |1|C| 

So when we resolve collisions they happen in this order:
1. resolve collisions with cyber truck by updating players final block to be behind cyber truck
2. resolve player on player collisions if their final blocks are the same

^ so because of this based on the original collision rules, player 1 and player 2's final block is the
